name: meetyarah
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  get: ^4.6.6
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  image_picker: ^1.0.4
  video_player: ^2.8.1
  http: ^1.1.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0

  # Downgraded packages to support older Flutter versions
  share_plus: ^7.2.0
  app_links: ^3.4.5
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.13.0
  url_launcher: ^6.2.0
  webview_flutter_web: 0.2.2+4
  android_intent_plus: ^4.0.0
  video_thumbnail: ^0.5.3
  faker: ^2.1.0
  flutter_stripe: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Downgraded lints as well

# No override needed if using these older versions

flutter:
  uses-material-design: true
  assets:
    - assets/images/